add list of brands using RN
nearform/react-native-workshop pull request #2
Opened 2023-10-25 12:08 UTC by codyzu

Added a list of brands in the community and clients using RN

2023-10-25 12:09 UTC, codyzu commented
Not sure where to put these slides or if we should add logos. TBD.

2023-10-25 12:17 UTC, codyzu commented on slides/slides.md
> +* Aer Lingus
```suggestion
* Aer Lingus
```

2023-10-25 12:17 UTC, codyzu commented on slides/slides.md
> +* Get Ireland
```suggestion
* Get Ireland Walking
```

2023-10-25 12:19 UTC, SociableSteve requested changes

2023-10-25 12:19 UTC, SociableSteve commented on slides/slides.md
> +* Microsoft: Office, Outlook, Teams, Xbox Game Pass, Skyp
Typo in Skype

2023-10-25 12:19 UTC, SociableSteve commented on slides/slides.md
> +* Many more...
Is there anything that this `many more...` can link to?

2023-10-25 12:19 UTC, SociableSteve commented on slides/slides.md
> +# Who's using it? - NearForm Partners
Not sure this is the best title - this reads as people we've worked with who are using it, not necessarily projects we have worked on.

2023-10-25 15:03 UTC, AlanSl requested changes
See comment on Slack!

2023-10-25 15:03 UTC, AlanSl commented on slides/slides.md
> +* Aer Lingus
```suggestion
```

2023-10-30 08:33 UTC, SociableSteve commented
Current slides:

<img width="1389" alt="image" src="https://github.com/nearform/react-native-workshop/assets/52213009/7d4811ed-1fc0-4056-9732-ee6bf558eeb6">
<img width="1381" alt="image" src="https://github.com/nearform/react-native-workshop/assets/52213009/7a32b2d8-f19d-4d7b-83c6-f0c7d6f06f7f">

2023-10-30 08:51 UTC, robwalkerco approved these changes
Looks good to me 🚢

2023-10-30 08:52 UTC, merged